#!/usr/bin/env bash
TERMINAL=kitty

declare -A menu=(
  ["brightness"]="$TERMINAL --class tv tv brightness"
  ["Clipboard"]="$HOME/.config/dmenu-scripts/clipboard.sh"
  ["Edit config"]="$TERMINAL --class tv tv dirs-config && $TERMINAL $EDITOR \"\$(xclip -selection secondary -out)\""
  ["Edit obsidian"]="$TERMINAL --class tv tv files-obsidian && $TERMINAL $EDITOR \"\$(xclip -selection secondary -out)\""
  ["Web search"]="$HOME/.config/dmenu-scripts/web-search.sh"
  ["Volume control"]="$TERMINAL --class pulsemixer -e $HOME/Desktop/pulsemixer"
  ["wifi"]="$TERMINAL --class wlctl -e wlctl"
)

selection=$(printf "%s\n" "${!menu[@]}" | rofi -dmenu -i)

[[ "$selection" == "Quit" || -z "$selection" ]] && exit 0

if [[ -n "${menu[$selection]}" ]]; then
  eval "${menu[$selection]}"
fi
