#!/usr/bin/env bash
TERMINAL=kitty

declare -A menu=(
  ["brightness"]="$HOME/.config/dmenu-scripts/brightness.sh"
  ["Clipboard"]="$HOME/.config/dmenu-scripts/clipboard.sh"
  ["Wifi"]="networkmanager_dmenu"
  ["Edit config"]="$TERMINAL --class tv tv dirs-config"
  ["Web search"]="$HOME/.config/dmenu-scripts/web-search.sh"
  ["Volume control"]="$TERMINAL --class pulsemixer -e $HOME/Desktop/pulsemixer"
  ["Edit obsidian"]="$TERMINAL --class tv tv files-obsidian"
)

selection=$(printf "%s\n" "${!menu[@]}" | rofi -dmenu -i)

[[ "$selection" == "Quit" || -z "$selection" ]] && exit 0

if [[ -n "${menu[$selection]}" ]]; then
  eval "${menu[$selection]}"
fi
