[metadata]
name = "dirs-config"
description = "A channel to select from config directories"
requirements = ["fd"]

[source]
command = "fd -t d --max-depth 4 . $HOME/.config $HOME/dotfiles"

[preview]
command = "ls -la --color=always '{}'"

[keybindings]
shortcut = "f2"
enter = "actions:open"

[actions.open]
description = "Copy selected path to clipboard"
command = "printf '%s' '{}' | xsel --clipboard --input"
shell = "bash"
mode = "execute"
