[metadata]
name = "files-obsidian"
description = "A channel to select obsidian files and directories"
requirements = ["fd", "bat"]

[source]
command = "fd -t f --full-path $HOME/obsidian/base/"

[preview]
command = "bat -n --color=always '{}'"
env = { BAT_THEME = "ansi" }

[keybindings]
shortcut = "f1"
enter = "actions:open"

[actions.open]
description = "Copy selected path to clipboard"
command = "printf '%s' '{}' | xsel --clipboard --input"
shell = "bash"
mode = "execute"
